import { employees } from "../schema/employees";

export const seedEmployees = [
  // Management
  {
    employeeCode: "MGR001",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@restaurant.com",
    phone: "+1-555-0101",
    role: "manager" as const,
    department: "management",
    hourlyRate: "35.00",
    overtimeRate: "52.50",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2020-03-15"),
    averageRating: "4.8",
    totalShiftsWorked: 750,
    totalHoursWorked: "6000",
    maxHoursPerWeek: 50,
    minHoursPerWeek: 40,
    canWorkWeekends: true,
    canWorkHolidays: true,
  },
  {
    employeeCode: "AMGR001",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@restaurant.com",
    phone: "+1-555-0102",
    role: "assistant_manager" as const,
    department: "management",
    hourlyRate: "28.00",
    overtimeRate: "42.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2021-06-20"),
    averageRating: "4.6",
    totalShiftsWorked: 450,
    totalHoursWorked: "3600",
    maxHoursPerWeek: 45,
    minHoursPerWeek: 35,
    canWorkWeekends: true,
    canWorkHolidays: true,
  },

  // Kitchen Staff
  {
    employeeCode: "CHEF001",
    firstName: "Antonio",
    lastName: "Rodriguez",
    email: "antonio.rodriguez@restaurant.com",
    phone: "+1-555-0201",
    role: "head_chef" as const,
    department: "kitchen",
    hourlyRate: "32.00",
    overtimeRate: "48.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2019-11-10"),
    averageRating: "4.9",
    totalShiftsWorked: 900,
    totalHoursWorked: "7200",
    maxHoursPerWeek: 50,
    minHoursPerWeek: 40,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "morning",
  },
  {
    employeeCode: "CHEF002",
    firstName: "Lisa",
    lastName: "Patel",
    email: "lisa.patel@restaurant.com",
    phone: "+1-555-0202",
    role: "sous_chef" as const,
    department: "kitchen",
    hourlyRate: "26.00",
    overtimeRate: "39.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2020-08-05"),
    averageRating: "4.7",
    totalShiftsWorked: 650,
    totalHoursWorked: "5200",
    maxHoursPerWeek: 45,
    minHoursPerWeek: 35,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "morning",
  },
  {
    employeeCode: "COOK001",
    firstName: "James",
    lastName: "Wilson",
    email: "james.wilson@restaurant.com",
    phone: "+1-555-0203",
    role: "line_cook" as const,
    department: "kitchen",
    hourlyRate: "18.00",
    overtimeRate: "27.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2022-01-15"),
    averageRating: "4.4",
    totalShiftsWorked: 350,
    totalHoursWorked: "2800",
    maxHoursPerWeek: 40,
    minHoursPerWeek: 30,
    canWorkWeekends: true,
    canWorkHolidays: false,
    preferredShift: "evening",
  },
  {
    employeeCode: "COOK002",
    firstName: "Maria",
    lastName: "Garcia",
    email: "maria.garcia@restaurant.com",
    phone: "+1-555-0204",
    role: "line_cook" as const,
    department: "kitchen",
    hourlyRate: "17.50",
    overtimeRate: "26.25",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2022-03-20"),
    averageRating: "4.3",
    totalShiftsWorked: 300,
    totalHoursWorked: "2400",
    maxHoursPerWeek: 40,
    minHoursPerWeek: 30,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "afternoon",
  },
  {
    employeeCode: "PREP001",
    firstName: "David",
    lastName: "Kim",
    email: "david.kim@restaurant.com",
    phone: "+1-555-0205",
    role: "prep_cook" as const,
    department: "kitchen",
    hourlyRate: "15.50",
    overtimeRate: "23.25",
    employmentType: "part_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2023-02-10"),
    averageRating: "4.2",
    totalShiftsWorked: 150,
    totalHoursWorked: "900",
    maxHoursPerWeek: 25,
    minHoursPerWeek: 15,
    canWorkWeekends: false,
    canWorkHolidays: false,
    preferredShift: "morning",
  },

  // Bar Staff
  {
    employeeCode: "BAR001",
    firstName: "Robert",
    lastName: "Taylor",
    email: "robert.taylor@restaurant.com",
    phone: "+1-555-0301",
    role: "head_bartender" as const,
    department: "bar",
    hourlyRate: "22.00",
    overtimeRate: "33.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2021-04-01"),
    averageRating: "4.8",
    totalShiftsWorked: 500,
    totalHoursWorked: "4000",
    maxHoursPerWeek: 40,
    minHoursPerWeek: 35,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "evening",
  },
  {
    employeeCode: "BAR002",
    firstName: "Emma",
    lastName: "Brown",
    email: "emma.brown@restaurant.com",
    phone: "+1-555-0302",
    role: "bartender" as const,
    department: "bar",
    hourlyRate: "18.00",
    overtimeRate: "27.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2022-06-15"),
    averageRating: "4.5",
    totalShiftsWorked: 250,
    totalHoursWorked: "2000",
    maxHoursPerWeek: 35,
    minHoursPerWeek: 25,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "night",
  },
  {
    employeeCode: "BAR003",
    firstName: "Jake",
    lastName: "Martinez",
    email: "jake.martinez@restaurant.com",
    phone: "+1-555-0303",
    role: "barback" as const,
    department: "bar",
    hourlyRate: "14.00",
    overtimeRate: "21.00",
    employmentType: "part_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2023-01-20"),
    averageRating: "4.1",
    totalShiftsWorked: 120,
    totalHoursWorked: "720",
    maxHoursPerWeek: 20,
    minHoursPerWeek: 10,
    canWorkWeekends: true,
    canWorkHolidays: false,
    preferredShift: "night",
  },

  // Service Staff
  {
    employeeCode: "SRV001",
    firstName: "Jennifer",
    lastName: "Davis",
    email: "jennifer.davis@restaurant.com",
    phone: "+1-555-0401",
    role: "head_server" as const,
    department: "service",
    hourlyRate: "16.00",
    overtimeRate: "24.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2020-09-01"),
    averageRating: "4.9",
    totalShiftsWorked: 600,
    totalHoursWorked: "4800",
    maxHoursPerWeek: 40,
    minHoursPerWeek: 32,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "evening",
  },
  {
    employeeCode: "SRV002",
    firstName: "Ashley",
    lastName: "Thompson",
    email: "ashley.thompson@restaurant.com",
    phone: "+1-555-0402",
    role: "server" as const,
    department: "service",
    hourlyRate: "12.00",
    overtimeRate: "18.00",
    employmentType: "full_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2021-11-10"),
    averageRating: "4.6",
    totalShiftsWorked: 400,
    totalHoursWorked: "3200",
    maxHoursPerWeek: 35,
    minHoursPerWeek: 25,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "afternoon",
  },
  {
    employeeCode: "SRV003",
    firstName: "Ryan",
    lastName: "Anderson",
    email: "ryan.anderson@restaurant.com",
    phone: "+1-555-0403",
    role: "server" as const,
    department: "service",
    hourlyRate: "12.00",
    overtimeRate: "18.00",
    employmentType: "part_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2022-05-20"),
    averageRating: "4.4",
    totalShiftsWorked: 200,
    totalHoursWorked: "1200",
    maxHoursPerWeek: 25,
    minHoursPerWeek: 15,
    canWorkWeekends: true,
    canWorkHolidays: false,
    preferredShift: "evening",
  },
  {
    employeeCode: "HOST001",
    firstName: "Sophia",
    lastName: "Lee",
    email: "sophia.lee@restaurant.com",
    phone: "+1-555-0404",
    role: "host" as const,
    department: "service",
    hourlyRate: "14.00",
    overtimeRate: "21.00",
    employmentType: "part_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2023-03-01"),
    averageRating: "4.3",
    totalShiftsWorked: 100,
    totalHoursWorked: "600",
    maxHoursPerWeek: 20,
    minHoursPerWeek: 10,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "evening",
  },
  {
    employeeCode: "BUS001",
    firstName: "Carlos",
    lastName: "Hernandez",
    email: "carlos.hernandez@restaurant.com",
    phone: "+1-555-0405",
    role: "busser" as const,
    department: "service",
    hourlyRate: "13.00",
    overtimeRate: "19.50",
    employmentType: "part_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2023-04-15"),
    averageRating: "4.0",
    totalShiftsWorked: 80,
    totalHoursWorked: "480",
    maxHoursPerWeek: 20,
    minHoursPerWeek: 10,
    canWorkWeekends: true,
    canWorkHolidays: false,
    preferredShift: "afternoon",
  },
  {
    employeeCode: "RUN001",
    firstName: "Tyler",
    lastName: "White",
    email: "tyler.white@restaurant.com",
    phone: "+1-555-0406",
    role: "food_runner" as const,
    department: "service",
    hourlyRate: "13.50",
    overtimeRate: "20.25",
    employmentType: "part_time" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2023-05-01"),
    averageRating: "4.1",
    totalShiftsWorked: 60,
    totalHoursWorked: "360",
    maxHoursPerWeek: 25,
    minHoursPerWeek: 10,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "evening",
  },

  // Part-time/Seasonal Staff
  {
    employeeCode: "SEAS001",
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily.johnson@restaurant.com",
    phone: "+1-555-0501",
    role: "server" as const,
    department: "service",
    hourlyRate: "12.00",
    overtimeRate: "18.00",
    employmentType: "seasonal" as const,
    employmentStatus: "active" as const,
    hireDate: new Date("2023-06-01"),
    averageRating: "4.2",
    totalShiftsWorked: 40,
    totalHoursWorked: "240",
    maxHoursPerWeek: 30,
    minHoursPerWeek: 15,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "afternoon",
    notes: "Summer seasonal staff - college student",
  },

  // Inactive/On Leave Staff
  {
    employeeCode: "COOK003",
    firstName: "Daniel",
    lastName: "Smith",
    email: "daniel.smith@restaurant.com",
    phone: "+1-555-0206",
    role: "line_cook" as const,
    department: "kitchen",
    hourlyRate: "19.00",
    overtimeRate: "28.50",
    employmentType: "full_time" as const,
    employmentStatus: "on_leave" as const,
    hireDate: new Date("2021-07-01"),
    averageRating: "4.5",
    totalShiftsWorked: 450,
    totalHoursWorked: "3600",
    maxHoursPerWeek: 40,
    minHoursPerWeek: 35,
    canWorkWeekends: true,
    canWorkHolidays: true,
    preferredShift: "morning",
    notes: "On medical leave - expected return in 2 months",
  },
];